version: '3.8'

services:
  face-play:
    image: tanminkwan/face-play
    container_name: face-play
    ports:
      - "7860:7860"
    environment:
      S3_ENDPOINT: mamama.iptime.org:9000
      S3_ACCESS_KEY: e1WvA6fH9N87tqoMw9qG
      S3_SECRET_KEY: DU9OYU32ZK2IH99lk4DaoyAopYBNqJMjp6IVJ6LS
      S3_SECURE: "false"
      S3_PROCESSED_IMAGE_BUCKET: processed-images
      VECTOR_DB: QDRANT
      VECTOR_DB_HOST: 172.17.0.1
      VECTOR_DB_PORT: "6333"
    command: ["python", "run_app.py"]
  face-play-scheduler:
    image: tanminkwan/face-play
    container_name: face-play-scheduler
    environment:
      S3_ENDPOINT: mamama.iptime.org:9000
      S3_ACCESS_KEY: e1WvA6fH9N87tqoMw9qG
      S3_SECRET_KEY: DU9OYU32ZK2IH99lk4DaoyAopYBNqJMjp6IVJ6LS
      S3_SECURE: "false"
      S3_PROCESSED_IMAGE_BUCKET: processed-images
      VECTOR_DB: QDRANT
      VECTOR_DB_HOST: 172.17.0.1
      VECTOR_DB_PORT: "6333"
    command: ["python", "run_scheduler.py"]